### ISSUE TITLE
File Picker Does Not Show Up

### ISSUE THREAD

**Issue by kdwk** [sarweshparajuli/nativefier-appimage#2]
After packaging a website into an Appimage, the file/ folder picker doesn't show up when downloading a file.
As tested on:
Fedora 33 (Gnome, x86_64, Wayland)

`appnativefy --name "WhatsApp" --url "https://web.whatsapp.com'`

`appnativefy --name "FileRoom" --url "https://fileroom.io'`

Note: the file picker shows up correctly when uploading files, and the file picker shows up correctly when downloading files in Mozilla Firefox

**Comment by sarwesh00** [comment]
Will be adding feature in next release, very soon.

**Comment by kdwk** [comment]
Ok then, thanks

**Comment by sarwesh00** [comment]
Could you install the new version, using `sudo npm i -g appnativefy` and build AppImages passing `--saveAs` flag.

**Comment by kdwk** [comment]
Update: the file actually gets downloaded, and shows up in the default Downloads folder, but does not show a file picker

**Comment by sarwesh00** [comment]
Yes that was intended

**Comment by kdwk** [comment]
> Could you install the new version, using `sudo npm i -g appnativefy` and build AppImages passing `--saveAs` flag.

It works now :-)
