### ISSUE TITLE
No Integration With Application Launcher

### ISSUE THREAD

**Issue by kdwk** [sarweshparajuli/nativefier-appimage#3]
First run of the Appimage does not trigger the 'Integrate with Desktop' option on Gnome, which allows the Appimage to be added to the App Launcher.
As tested on:
Fedora 33 (Gnome, Wayland, x86_64)
For all Appimages

**Comment by sarwesh00** [comment]
This seems like an issue with your DE.

Can you check if your DE has made the desktop file?
`~/. local/share/applications/ ` 

or

`/usr/local/share/applications/ `

**Comment by kdwk** [comment]
![Screenshot from 2021-02-17 13-19-30](https://user-images.githubusercontent.com/39268094/108159826-cb62ab00-7122-11eb-85c5-622cb90a1ff0.png)
The folder in question after packaging web.whatsapp.com as an Appimage.
Answering your question, no, I don't think so.
Thanks for the quick response.

**Comment by sarwesh00** [comment]
Regarding the Desktop entry, i'll be adding a built in feature in another release, after looking more into it.

**Comment by kdwk** [comment]
Ok thanks

**Comment by yochananmarqos** [comment]
There's always [AppImageLauncher.](https://github.com/TheAssassin/AppImageLauncher)
