### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by alexmyczko** [sarweshparajuli/nativefier-appimage#4]
Can you create a web page with a form to create them?

Here is a fee examples I will try when I would like to see:

https://aiei.ch/airports/

http://shell.aiei.ch/typography/

**Comment by sarwesh00** [comment]
> Can you create a web page with a form to create them?

Do you mean to make a website that will generate the command to use for a specific website?

<br>
Anyways, 

For [https://aiei.ch/airports/](https://aiei.ch/airports/):
```
appnativefy --name "Airports" --url "https://aiei.ch/airports/" --favicon
```

(We passed `--favicon` to force use the favicon, it is optional)



For [http://shell.aiei.ch/typography/](http://shell.aiei.ch/typography/):
```
appnativefy --name "Font Specimen Creator" --url "http://shell.aiei.ch/typography/"
```

(This site does not have a favicon, so `--favicon` not passed.
