### ISSUE TITLE
Feature request: Integrate locally hosted sites with Python in appnativefy

### ISSUE THREAD

**Issue by gnutechie** [sarweshparajuli/nativefier-appimage#6]
As I see it the app basically creates site "vessels" in the sense that it's basically another Chromium/Electron browser instance for a site that's already deployed etc etc.

Would it not be possible to do this with html or PHP pages or even Markdown pages hosted on a local http session through Python?

We already know that:
 `python -m SimpleHTTPServer 8888 --bind localhost --directory <site-dir>`
 or
 `python3 -m http.server 8888 --bind localhost --directory <site-dir>`
 
 will create a local web server listening on port 8888... is it not possible to enable this option on appnativefy so as to create nativefied locally hosted web apps... this could also be used in kiosk mode or perhaps... digital signage and other use cases... in my opinion it can expand the scope of the app.
 
 What are your thoughts?

**Comment by sarwesh00** [comment]
Assuming that your python server is already running,

You could simply run `appnativefy --name "localhost" --url "https://localhost:8888"`

You can replace `localhost` in  `--name "localhost"` with your desired name.

**Comment by gnutechie** [comment]
I understand that, but what I'm talking about is bundling the html/css/js/php/image files in the appimage and running the python commands I suggested above after copying the site files to another directory or in /temp.

Do you think that might be a useful feature to add to this app?

**Comment by sarwesh00** [comment]
I think so, will be adding the feature soon

**Comment by gnutechie** [comment]
Awesome thank you for your consideration :) :+1:
