### ISSUE TITLE
Is it possible to nativefy a website thoroughly for offline usage?

### ISSUE THREAD

**Issue by unexploredtest** [sarweshparajuli/nativefier-appimage#7]
Like for example, a website like https://pytorch.org/tutorials/ , whith `appnativefy --name "PyTorch-Tutorials" --url "https://pytorch.org/tutorials"` it's not possible to access "https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html" while offline, is there an option which enables it?

**Comment by sarwesh00** [comment]
Well, no, however I may implement that feature if the sitemap is provided, in the future.
