### ISSUE TITLE
Persistent logins

### ISSUE THREAD

**Issue by distek** [sarweshparajuli/nativefier-appimage#8]
Hey, thanks for this. It's really cool.

Not sure if I'm missing it, but is there a way to have session cookies/logins persist between launches?

**Comment by sarwesh00** [comment]
If the website supports cookies, as far as I am aware, it doessave the cookies unless the website does not support it.


Could you give more details into your problem?

**Comment by distek** [comment]
I must have been on a different train of thought, because this is actually how it normally works with this particular web app (protonmail). It would be neat to have saved passwords, but I can open another issue for that.
